name: "build android"

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;28.0.12674087"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Build apk
        run: |
          cargo apk build -p callme-egui --target aarch64-linux-android --lib --release
        env:
          ANDROID_NDK: ${{ env.ANDROID_HOME }}/ndk/28.0.12433566
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK }}
          TOOLCHAIN: ${{ env.ANDROID_NDK }}/toolchains/llvm/prebuilt/linux-x86_64
          CARGO_APK_RELEASE_KEYSTORE_PASSWORD: android
          CARGO_APK_RELEASE_KEYSTORE: ${{ env.HOME }}/.android/debug.keystore

      - uses: actions/upload-artifact@v4
        with:
          name: callme-egui.apk
          path: ./target/release/apk/callme-egui.apk
