name: "build android"

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-30"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-apk

      - name: Build apk
        run: |
          keytool -genkey -v -keystore /tmp/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
          cargo apk build -p callme-egui --target aarch64-linux-android --lib --release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          TOOLCHAIN: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64
          CARGO_APK_RELEASE_KEYSTORE_PASSWORD: android
          CARGO_APK_RELEASE_KEYSTORE: /tmp/debug.keystore

      - uses: actions/upload-artifact@v4
        with:
          name: callme-egui.apk
          path: ./target/release/apk/callme-egui.apk
